app_config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    # 今回作成するアプリ「app_folder」にアクセスするURL
    path('app_folder/', include('app_folder.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    # 何もURLを指定しない場合（app_config/views.pyで、自動的に「app_folder」にアクセスするよう設定済み）
    path('', views.index, name='index'),
    # 管理サイトにアクセスするURL
    path('admin_workflow_hopnic/', admin.site.urls),
]

# メディアファイル公開用のURL設定
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_folder/urls.py
from django.urls import path
from . import views

app_name = 'app_folder'
urlpatterns = [
    path('top_page/', views.top_listing, name='top_page'),
    path('request_list/', views.request_listing, name='request_list'),
    path('request_list2/', views.request_list2, name='request_list2'),
    path('request_list3/', views.request_list3, name='request_list3'),
    path('request_create/', views.request_create, name='request_create'),
    path('request_detail/<uuid:pk>', views.request_detail, name='request_detail'),
    path('request_delete/<uuid:pk>', views.request_delete, name='request_delete'),
    path('request_update/<uuid:pk>', views.request_update, name='request_update'),
    path('approval_list/', views.approval_list, name='approval_list'),
    path('approval_detail/<uuid:pk>', views.approval_detail, name='approval_detail'),
    path('approval_update/<uuid:pk>', views.approval_update, name='approval_update'),
    path('last_approval_detail/<uuid:pk>', views.last_approval_detail, name='last_approval_detail'),
    path('last_approval_update/<uuid:pk>', views.last_approval_update, name='last_approval_update'),
    path('last_approval_list/', views.last_approval_list, name='last_approval_list'),
    path('info_detail/<uuid:pk>', views.info_detail, name='info_detail'),
    path('info_create/', views.info_create, name='info_create'),
    path('info_delete/<uuid:pk>', views.info_delete, name='info_delete'),
    path('info_update/<uuid:pk>', views.info_update, name='info_update'),
    path('info_confirm/<uuid:if_id>', views.info_confirm, name='info_confirm'),
    path('offday_list/', views.offday_listing, name='offday_list'),
    path('offday_list2/', views.offday_list2, name='offday_list2'),
    path('offday_list3/', views.offday_list3, name='offday_list3'),
    path('offday_create/', views.offday_create, name='offday_create'),
    path('offday_detail/<uuid:pk>', views.offday_detail, name='offday_detail'),
    path('offday_delete/<uuid:pk>', views.offday_delete, name='offday_delete'),
    path('ap_offday_list/', views.ap_offday_list, name='ap_offday_list'),
    path('ap_offday_update/<uuid:pk>', views.ap_offday_update, name='ap_offday_update'),
    path('ls_offday_list/', views.ls_offday_list, name='ls_offday_list'),
    path('ls_offday_update/<uuid:pk>', views.ls_offday_update, name='ls_offday_update'),
    path('logout/', views.logout_view, name='logout'),
    path('diningroom/', views.diningroom, name='diningroom'),
    path('meetingroom/', views.meetingroom, name='meetingroom'),
    path('calendar/', views.calendar, name='calendar'),
    path('message/', views.message, name='message'),
    path('kaizen/', views.improvement_create, name='improvement_create'),
    # path('kaizenEXCEL/', views.export_improvementdata_excel, name='kaizenEXCEL'),
    path('improve_list/', views.improve_list, name='improve_list'),
    path('improve_list2/', views.improve_list2, name='improve_list2'),
    path('improve_detail/<uuid:pk>', views.improve_detail, name='improve_detail'),
    path('improve_update1/<uuid:pk>', views.improve_update1, name='improve_update1'),
    path('improve_update2/<uuid:pk>', views.improve_update2, name='improve_update2'),
    path('iken/', views.opinion_create, name='opinion_create'),
#    path('improve_pdf/<uuid:pk>', views.improve_pdf, name='improve_pdf'),
    path("import_offday_csv/", views.import_offday_csv, name="import_offday_csv"),
    path("bulk_update_offday/", views.bulk_update_offday, name="bulk_update_offday"),
    path("bulk_update_offday2/", views.bulk_update_offday2, name="bulk_update_offday2"),
]

app_folder/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
import uuid


class RequestMst(models.Model):
    class Meta:
        db_table = 'RequestMst' # DB内で使用するテーブル名
        verbose_name_plural = '申請マスタ' # Admionサイトで表示するテーブル名
    requestID = models.CharField('項目ID', max_length=5,primary_key=True,null=False, blank=True)
    RequestType = models.CharField('申請項目名', max_length=255, null=True, blank=True) # 文字列を格納
    needMeeting = models.BooleanField('要会議招集',default=False)
    needRingi = models.BooleanField('要稟議書',default=False)
    chkJimu = models.BooleanField('要事務所確認',default=False)
    del_flg = models.BooleanField(
        verbose_name=_("削除フラグ"),
        default=False
    )
    def __str__(self):
        return self.RequestType

class RequestData(models.Model):
    choice_ap = (
        (0, "未承認"),
        (1, "承認済"),
        (2, "却下"),
    )

    class Meta:
        db_table = 'RequestData' # DB内で使用するテーブル名
        verbose_name_plural = '申請データ' # Admionサイトで表示するテーブル名
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    requestID = models.ForeignKey(
        RequestMst,
        on_delete=models.SET_NULL,
        verbose_name='申請項目',
        null=True,
        blank=False,
    )
    rq_account_id = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True, 
        blank=True
    ) 
    usermei = models.CharField(
        max_length=40,
        null=True,
        blank=True
    )
    user_email = models.EmailField(
        null=True,
        blank=True
    )
    ReqDate = models.DateTimeField(blank=False, null=False, auto_now_add=True)
    update_at = models.DateTimeField(blank=False, null=False, auto_now=True)
    content = models.TextField(
        verbose_name='内容',
        null=True,
        blank=True,
    )
    attach = models.FileField(
        upload_to='uploads/%Y/%m/%d/',
        verbose_name='添付ファイル',
        null=True,
        blank=True,
    )
    approval_id = models.IntegerField(
        null=True,
        blank=True
    )
    apmei = models.CharField(
        max_length=40,
        null=True,
        blank=True
    )
    ap_email = models.EmailField(
        null=True,
        blank=True
    )
    approval_content = models.TextField(
        verbose_name=_("コメント"),
        null=True,
        blank=True,        
    )
    approval = models.IntegerField(
        verbose_name=_("承認"),
        default=0,
        choices=choice_ap,        
    )
    approval_read = models.BooleanField(default=False)
    last_approval_id = models.IntegerField(
        null=True,
        blank=True
    )
    lsmei = models.CharField(
        max_length=40,
        null=True,
        blank=True
    )
    ls_email = models.EmailField(
        null=True,
        blank=True
    )
    last_approval_content = models.TextField(
        verbose_name=_("コメント"),
        null=True,
        blank=True,
    )
    last_approval = models.IntegerField(
        verbose_name=_("最終承認"),
        default=0,
        choices=choice_ap,        
    )
    last_read = models.BooleanField(default=False)
    withdrawal = models.BooleanField(default=False)
    withdrawal_id = models.IntegerField(
        verbose_name=_("最終承認者"),
        null=True,
        blank=True
    )
    attach2 = models.FileField(
        upload_to='uploads/%Y/%m/%d/',
        verbose_name='添付ファイル',
        null=True,
        blank=True,
    )
    attach3 = models.FileField(
        upload_to='uploads/%Y/%m/%d/',
        verbose_name='添付ファイル',
        null=True,
        blank=True,
    )
    ap_no = models.CharField(
        max_length=10,
        null=True,
        blank=True
    )
    chkJimu = models.BooleanField('要事務所確認',default=False)
    def __str__(self):
        return self.usermei

class ApprovalMst(models.Model):
    choices=[(i.id, i.first_name) for i in User.objects.all()]
    class Meta:
        db_table = 'ApprovalMst' # DB内で使用するテーブル名
        verbose_name_plural = '承認者マスタ' # Admionサイトで表示するテーブル名
    userid = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        verbose_name=_("ユーザー"),
        primary_key=True,
        unique=True,
        max_length=10,
    )
    umei = models.CharField(
        verbose_name=_("氏名"),
        max_length=40,
        null=True,
        blank=True
    )
    approval_id = models.IntegerField(
        verbose_name=_("承認者"),
        null=True,
        choices=choices,        
        blank=True
    )
    apmei = models.CharField(
        verbose_name=_("承認者氏名"),
        max_length=40,
        null=True,
        blank=True
    )
    ap_email = models.EmailField(
        verbose_name=_("承認者email"),
        null=True,
        blank=True
    )
    last_approval_id = models.IntegerField(
        verbose_name=_("最終承認者"),
        null=True,
        choices=choices,        
        blank=True
    )
    lsmei = models.CharField(
        verbose_name=_("最終承認者氏名"),
        max_length=40,
        null=True,
        blank=True
    )
    last_email = models.EmailField(
        verbose_name=_("最終承認email"),
        null=True,
        blank=True
    )
    del_flg = models.BooleanField(
        verbose_name=_("削除フラグ"),
        default=False
    )
    def __str__(self):
        return self.umei

class InfoData(models.Model):
    class Meta:
        db_table = 'InfoData' # DB内で使用するテーブル名
        verbose_name_plural = '案内データ' # Admionサイトで表示するテーブル名
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    if_account_id = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=False, 
        blank=True
    ) 
    usermei = models.CharField(
        max_length=40,
        null=True,
        blank=True
    )
    user_email = models.EmailField(
        null=True,
        blank=True
    )
    ReqDate = models.DateTimeField(blank=False, null=False, auto_now_add=True)
    update_at = models.DateTimeField(blank=False, null=False, auto_now=True)
    title = models.CharField(
        max_length=60,
        null=True,
        blank=False,
    )
    content = models.TextField(
        verbose_name='内容',
        null=True,
        blank=False,
    )
    attach = models.FileField(
        upload_to='uploads/%Y/%m/%d/',
        verbose_name='添付ファイル',
        null=True,
        blank=True,
    )
    permission = models.BooleanField(
        verbose_name='全従業員閲覧可',
        default=False
        )
    image = models.FileField(
        upload_to='uploads/%Y/%m/%d/',
        verbose_name='画像添付',
        null=True,
        blank=True,
    )
    pdf = models.FileField(
        upload_to='uploads/%Y/%m/%d/',
        verbose_name='PDF添付',
        null=True,
        blank=True,
    )
    def __str__(self):
        return self.title

class DepartmentMst(models.Model):
    class Meta:
        db_table = 'DepartmentMst' # DB内で使用するテーブル名
        verbose_name_plural = '部署マスタ' # Admionサイトで表示するテーブル名
    dmei = models.CharField(
        verbose_name=_("部署名"),
        max_length=40,
        null=True,
        blank=True
    )
    def __str__(self):
        return self.dmei

class EmployeeMst(models.Model):
    class Meta:
        db_table = 'EmployeeMst' # DB内で使用するテーブル名
        verbose_name_plural = '従業員マスタ' # Admionサイトで表示するテーブル名
    emmei = models.CharField(
        verbose_name=_("従業員名"),
        max_length=40,
        null=True,
        blank=True
    )
    d_id = models.ForeignKey(
        DepartmentMst,
        on_delete=models.SET_NULL,
        null=True, 
        blank=True
    ) 
    email = models.EmailField(
        null=True,
        blank=True
    )
    del_flg = models.BooleanField(
        verbose_name=_("削除フラグ"),
        default=False
    )
    def __str__(self):
        return self.emmei

class OffdayRequestMst(models.Model):
    class Meta:
        db_table = 'OffdayRequestMst' # DB内で使用するテーブル名
        verbose_name_plural = '勤怠申請対象者マスタ' # Admionサイトで表示するテーブル名
    u_id = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        verbose_name=_("勤怠申請者"),
        null=True, 
        blank=True
    ) 
    emmei = models.CharField(
        verbose_name=_("従業員名"),
        max_length=40,
        null=True,
        blank=True
    )
    del_flg = models.BooleanField(
        verbose_name=_("削除フラグ"),
        default=False
    )
    def __str__(self):
        return self.emmei

class PeriodMst(models.Model):
    class Meta:
        db_table = 'PeriodMst' # DB内で使用するテーブル名
        verbose_name_plural = '期間マスタ' # Admionサイトで表示するテーブル名
    period = models.CharField(
        verbose_name=_("期間"),
        max_length=40,
        null=True,
        blank=True
    )
    del_flg = models.BooleanField(
        verbose_name=_("削除フラグ"),
        default=False
    )
    def __str__(self):
        return self.period

class OffdayKbnMst(models.Model):
    class Meta:
        db_table = 'OffdayKbnMst' # DB内で使用するテーブル名
        verbose_name_plural = '勤怠区分マスタ' # Admionサイトで表示するテーブル名
    kbnmei = models.CharField(
        verbose_name=_("勤怠区分"),
        max_length=40,
        null=True,
        blank=True
    )
    del_flg = models.BooleanField(
        verbose_name=_("削除フラグ"),
        default=False
    )
    def __str__(self):
        return self.kbnmei

class OffDayData(models.Model):
    choice_ap = (
        (0, "未承認"),
        (1, "承認済"),
        (2, "却下"),
    )

    class Meta:
        db_table = 'OffDayData' # DB内で使用するテーブル名
        verbose_name_plural = '勤怠申請データ' # Admionサイトで表示するテーブル名
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    od_account_id = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True, 
        blank=True
    ) 
    usermei = models.CharField(
        max_length=40,
        null=True,
        blank=True
    )
    user_email = models.EmailField(
        null=True,
        blank=True
    )
    emp_id = models.ForeignKey(

templates/app_folder/info_confirm.html
{% extends 'base.html' %}
{% block contents %}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center mt-5 border-bottom">
    <h1 class="h2">返信フォーム</h1>
</div>

<div>
    <form method="POST" class= "form-group m-3" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="id_content">内容:</label>
        <textarea name="content" cols="40" rows="10" class="form-control p-1 m-3" id="id_content"></textarea>
        <input type='hidden' name='info' value="{{info.uuid}}">
        <button class="btn btn-primary btn-lg m-1"type="submit">送信</button>
        <p></p>
    </form>
</div>
<script>
</script>

{% endblock %}

templates/app_folder/message.html
{% extends 'base.html' %}
{% block contents %}

<h4>送信されました。</h4>

{% endblock %}

templates/app_folder/request_create.html
{% extends 'base.html' %}
{% block contents %}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center mt-5 border-bottom">
    <h1 class="h2">申請フォーム</h1>
</div>

<div>
    <p id="errmsg"></p>
    <p id="errmsg2"></p>
    <form method="POST" class= "form-group m-3" enctype="multipart/form-data"  autocomplete="off">
        {% csrf_token %}
        {{ form.as_p }}
        <div>
            <img id="img" src="" alt="画像プレビュー" style="width: 400px; height: 400px; object-fit: contain; display: none;" class="m-1">
            <!-- PDFプレビュー -->
            <iframe id="pdf-preview" style="width: 100%; height: 500px; display: none;" class="m-1"></iframe>
            <!-- Excelプレビュー -->
            <div id="excel-preview" style="width: 100%; height: 500px; overflow: auto; display: none; border: 1px solid #ccc;" class="m-1"></div>
            <img id="img2" src="" alt="画像プレビュー" style="width: 400px; height: 400px; object-fit: contain; display: none;" class="m-1">
            <!-- PDFプレビュー -->
            <iframe id="pdf-preview2" style="width: 100%; height: 500px; display: none;" class="m-1"></iframe>
            <!-- Excelプレビュー -->
            <div id="excel-preview2" style="width: 100%; height: 500px; overflow: auto; display: none; border: 1px solid #ccc;" class="m-1"></div>
            <img id="img3" src="" alt="画像プレビュー" style="width: 400px; height: 400px; object-fit: contain; display: none;" class="m-1">
            <!-- PDFプレビュー -->
            <iframe id="pdf-preview3" style="width: 100%; height: 500px; display: none;" class="m-1"></iframe>
            <!-- Excelプレビュー -->
            <div id="excel-preview3" style="width: 100%; height: 500px; overflow: auto; display: none; border: 1px solid #ccc;" class="m-1"></div>
        </div>
        <button class="btn btn-primary btn-lg m-1"type="submit">送信</button>
    </form>
</div>
<script>
    function requestCng() {
        var reqval = document.getElementById('id_requestID').value
        document.getElementById('errmsg').innerHTML = ""
        document.getElementById('errmsg2').innerHTML = ""
        {% for req in form.fields.requestID.queryset %}
        if ("{{ req.requestID }}" == reqval) {
            {% if req.needMeeting  %}
                document.getElementById('errmsg').innerHTML = "本申請内容は会議招集が必要な項目です。関係者に対して会議招集を行ってください。"
            {% endif %}
            {% if req.needRingi  %}
                document.getElementById('errmsg2').innerHTML = "本申請内容は稟議書が必要な項目です。稟議書を添付してください。"
            {% endif %}
        }
        {% endfor %}
    }
    document.addEventListener("DOMContentLoaded", function () {
        requestCng();
        const fileInput = document.querySelector("#id_attach");
        const previewImage = document.querySelector("#img");
        const previewPDF = document.querySelector("#pdf-preview");
        const previewExcel = document.querySelector("#excel-preview");
        const fileInput2 = document.querySelector("#id_attach2");
        const previewImage2 = document.querySelector("#img2");
        const previewPDF2 = document.querySelector("#pdf-preview2");
        const previewExcel2 = document.querySelector("#excel-preview2");
        const fileInput3 = document.querySelector("#id_attach3");
        const previewImage3 = document.querySelector("#img3");
        const previewPDF3 = document.querySelector("#pdf-preview3");
        const previewExcel3 = document.querySelector("#excel-preview3");
        document.getElementById('id_requestID').addEventListener("change", async (event) => {
            requestCng();
        });
    
        if (!fileInput || !previewImage || !previewPDF || !previewExcel ||!fileInput2 || !previewImage2 || !previewPDF2 || !previewExcel2 || !fileInput3 || !previewImage3 || !previewPDF3 || !previewExcel3) return; // 要素が存在しない場合は処理をしない
    
        fileInput.addEventListener("change", async (event) => {
            const file = event.target.files[0];
    
            // 何も選択されていない場合はすべて非表示
            if (!file) {
                previewImage.style.display = "none";
                previewPDF.style.display = "none";
                previewExcel.style.display = "none";
                return;
            }
    
            // ファイルのMIMEタイプを取得
            const fileType = file.type;
    
            // 画像ファイルの場合
            if (fileType.startsWith("image/")) {
                const reader = new FileReader();
                reader.onload = (e) => {
                    previewImage.src = e.target.result;
                    previewImage.style.display = "block"; // 画像を表示
                    previewPDF.style.display = "none"; // PDFを非表示
                    previewExcel.style.display = "none"; // Excelを非表示
                };
                reader.readAsDataURL(file);
            }
            // PDFファイルの場合
            else if (fileType === "application/pdf") {
                const reader = new FileReader();
                reader.onload = (e) => {
                    previewPDF.src = e.target.result;
                    previewPDF.style.display = "block"; // PDFを表示
                    previewImage.style.display = "none"; // 画像を非表示
                    previewExcel.style.display = "none"; // Excelを非表示
                };
                reader.readAsDataURL(file);
            }
            // Excelファイルの場合
            else if (
                file.name.endsWith(".xlsx") ||
                file.name.endsWith(".xls")
            ) {
                if (file.size > 1 * 1024 * 1024) { // 1MB以上の場合は処理しない
                    alert('ファイルサイズが大きすぎます。1MB以下のファイルを選択してください。');
                    event.target.value = ''; // ファイル選択をリセット
                    return;
                }
                previewImage.style.display = "none"; // 画像を非表示
                previewPDF.style.display = "none"; // PDFを非表示
                previewExcel.style.display = "block"; // Excelを表示
    
                const reader = new FileReader();
                reader.onload = async (e) => {
                    const data = new Uint8Array(e.target.result);
                    const workbook = XLSX.read(data, { type: "array" });
                    const sheetName = workbook.SheetNames[0]; // 最初のシート
                    const worksheet = workbook.Sheets[sheetName];
                    const htmlTable = XLSX.utils.sheet_to_html(worksheet);
                    previewExcel.innerHTML = htmlTable;
                };
                reader.readAsArrayBuffer(file);
            }
            // 画像・PDF・Excel以外の場合 → すべて非表示
            else {
                previewImage.style.display = "none";
                previewPDF.style.display = "none";
                previewExcel.style.display = "none";
            }
        });
        fileInput2.addEventListener("change", async (event) => {
            const file = event.target.files[0];
    
            // 何も選択されていない場合はすべて非表示
            if (!file) {
                previewImage2.style.display = "none";
                previewPDF2.style.display = "none";
                previewExcel2.style.display = "none";
                return;
            }
    
            // ファイルのMIMEタイプを取得
            const fileType = file.type;
    
            // 画像ファイルの場合
            if (fileType.startsWith("image/")) {
                const reader = new FileReader();
                reader.onload = (e) => {
                    previewImage2.src = e.target.result;
                    previewImage2.style.display = "block"; // 画像を表示
                    previewPDF2.style.display = "none"; // PDFを非表示
                    previewExcel2.style.display = "none"; // Excelを非表示
                };
                reader.readAsDataURL(file);
            }
            // PDFファイルの場合
            else if (fileType === "application/pdf") {
                const reader = new FileReader();
                reader.onload = (e) => {
                    previewPDF2.src = e.target.result;
                    previewPDF2.style.display = "block"; // PDFを表示
                    previewImage2.style.display = "none"; // 画像を非表示
                    previewExcel2.style.display = "none"; // Excelを非表示
                };
                reader.readAsDataURL(file);
            }
            // Excelファイルの場合
            else if (
                file.name.endsWith(".xlsx") ||
                file.name.endsWith(".xls")
            ) {
                previewImage2.style.display = "none"; // 画像を非表示
                previewPDF2.style.display = "none"; // PDFを非表示
                previewExcel2.style.display = "block"; // Excelを表示
    
                if (file.size > 1 * 1024 * 1024) { // 1MB以上の場合は処理しない
                    alert('ファイルサイズが大きすぎます。1MB以下のファイルを選択してください。');
                    event.target.value = ''; // ファイル選択をリセット
                    return;
                }

                const reader = new FileReader();
                reader.onload = async (e) => {
                    const data = new Uint8Array(e.target.result);
                    const workbook = XLSX.read(data, { type: "array" });
                    const sheetName = workbook.SheetNames[0]; // 最初のシート
                    const worksheet = workbook.Sheets[sheetName];
                    const htmlTable = XLSX.utils.sheet_to_html(worksheet);
                    previewExcel2.innerHTML = htmlTable;
                };
                reader.readAsArrayBuffer(file);
            }
            // 画像・PDF・Excel以外の場合 → すべて非表示
            else {
                previewImage2.style.display = "none";
                previewPDF2.style.display = "none";
                previewExcel2.style.display = "none";
            }
        });
        fileInput3.addEventListener("change", async (event) => {
            const file = event.target.files[0];
    
            // 何も選択されていない場合はすべて非表示
            if (!file) {
                previewImage3.style.display = "none";
                previewPDF3.style.display = "none";
                previewExcel3.style.display = "none";
                return;
            }
    
            // ファイルのMIMEタイプを取得
            const fileType = file.type;
    
            // 画像ファイルの場合
            if (fileType.startsWith("image/")) {
                const reader = new FileReader();
                reader.onload = (e) => {
                    previewImage3.src = e.target.result;
                    previewImage3.style.display = "block"; // 画像を表示
                    previewPDF3.style.display = "none"; // PDFを非表示
                    previewExcel3.style.display = "none"; // Excelを非表示
                };
                reader.readAsDataURL(file);
            }
            // PDFファイルの場合
            else if (fileType === "application/pdf") {
                const reader = new FileReader();
                reader.onload = (e) => {
                    previewPDF3.src = e.target.result;
                    previewPDF3.style.display = "block"; // PDFを表示
                    previewImage3.style.display = "none"; // 画像を非表示
                    previewExcel3.style.display = "none"; // Excelを非表示
                };
                reader.readAsDataURL(file);
            }
            // Excelファイルの場合
            else if (
                file.name.endsWith(".xlsx") ||
                file.name.endsWith(".xls")
            ) {
                previewImage3.style.display = "none"; // 画像を非表示
                previewPDF3.style.display = "none"; // PDFを非表示
                previewExcel3.style.display = "block"; // Excelを表示
    
                if (file.size > 1 * 1024 * 1024) { // 1MB以上の場合は処理しない
                    alert('ファイルサイズが大きすぎます。1MB以下のファイルを選択してください。');
                    event.target.value = ''; // ファイル選択をリセット
                    return;
                }
                
                const reader = new FileReader();
                reader.onload = async (e) => {
                    const data = new Uint8Array(e.target.result);
                    const workbook = XLSX.read(data, { type: "array" });
                    const sheetName = workbook.SheetNames[0]; // 最初のシート
                    const worksheet = workbook.Sheets[sheetName];
                    const htmlTable = XLSX.utils.sheet_to_html(worksheet);
                    previewExcel3.innerHTML = htmlTable;
                };
                reader.readAsArrayBuffer(file);
            }
            // 画像・PDF・Excel以外の場合 → すべて非表示
            else {
                previewImage3.style.display = "none";
                previewPDF3.style.display = "none";
                previewExcel3.style.display = "none";
            }
        });
    });
    
</script>

{% endblock %}

templates/app_folder/top_page.html
{% extends 'base.html' %}
{% block contents %}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center mt-5 border-bottom">
    <h1 class="h2">掲示板</h1>
</div>
{% if user.id != EMP_ID %}
<a href="{% url 'app_folder:info_create' %}" class="btn btn-primary btn-lg m-1" id="insirt">掲示板入力</a>
{% endif %}
<ul class="list-group">
    {% for object in page_obj %}
        <li class="p-1 m-1 list-group-item list-group-item-action">
            <a href="{% url 'app_folder:info_detail' object.pk %}">
                <h6>{{ object.title }}</h6>
            </a>
            <p>{{ object.ReqDate }}　　{{ object.usermei }}</p>
        </li>
    {% endfor %}
</ul>
  <nav aria-label="Page navigation example" class="mt-2">

    <ul class="pagination justify-content-center pagination-lg g-mt-28 g-mb-28">
        <!-- 前へ の部分 -->
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}

        <!-- 数字の部分 -->
        {% for num in page_obj.paginator.page_range %}
            {% if num <= page_obj.number|add:5 and num >= page_obj.number|add:-5 %}

                {% if page_obj.number == num %}
                    <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                {% endif %}
            {% endif %}
        {% endfor %}

        <!-- 次へ の部分 -->
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% endif %}
    </ul>

</nav>
</div>

{% endblock %}