app_config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    # 今回作成するアプリ「app_folder」にアクセスするURL
    path('app_folder/', include('app_folder.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    # 何もURLを指定しない場合（app_config/views.pyで、自動的に「app_folder」にアクセスするよう設定済み）
    path('', views.index, name='index'),
    # 管理サイトにアクセスするURL
    path('admin_workflow_hopnic/', admin.site.urls),
]

# メディアファイル公開用のURL設定
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_folder/urls.py
from django.urls import path
from . import views

app_name = 'app_folder'
urlpatterns = [
    path('top_page/', views.top_listing, name='top_page'),
    path('request_list/', views.request_listing, name='request_list'),
    path('request_list2/', views.request_list2, name='request_list2'),
    path('request_list3/', views.request_list3, name='request_list3'),
    path('request_create/', views.request_create, name='request_create'),
    path('request_detail/<uuid:pk>', views.request_detail, name='request_detail'),
    path('request_delete/<uuid:pk>', views.request_delete, name='request_delete'),
    path('request_update/<uuid:pk>', views.request_update, name='request_update'),
    path('approval_list/', views.approval_list, name='approval_list'),
    path('approval_detail/<uuid:pk>', views.approval_detail, name='approval_detail'),
    path('approval_update/<uuid:pk>', views.approval_update, name='approval_update'),
    path('last_approval_detail/<uuid:pk>', views.last_approval_detail, name='last_approval_detail'),
    path('last_approval_update/<uuid:pk>', views.last_approval_update, name='last_approval_update'),
    path('last_approval_list/', views.last_approval_list, name='last_approval_list'),
    path('info_detail/<uuid:pk>', views.info_detail, name='info_detail'),
    path('info_create/', views.info_create, name='info_create'),
    path('info_delete/<uuid:pk>', views.info_delete, name='info_delete'),
    path('info_update/<uuid:pk>', views.info_update, name='info_update'),
    path('info_confirm/<uuid:if_id>', views.info_confirm, name='info_confirm'),
    path('offday_list/', views.offday_listing, name='offday_list'),
    path('offday_list2/', views.offday_list2, name='offday_list2'),
    path('offday_list3/', views.offday_list3, name='offday_list3'),
    path('offday_create/', views.offday_create, name='offday_create'),
    path('offday_detail/<uuid:pk>', views.offday_detail, name='offday_detail'),
    path('offday_delete/<uuid:pk>', views.offday_delete, name='offday_delete'),
    path('ap_offday_list/', views.ap_offday_list, name='ap_offday_list'),
    path('ap_offday_update/<uuid:pk>', views.ap_offday_update, name='ap_offday_update'),
    path('ls_offday_list/', views.ls_offday_list, name='ls_offday_list'),
    path('ls_offday_update/<uuid:pk>', views.ls_offday_update, name='ls_offday_update'),
    path('logout/', views.logout_view, name='logout'),
    path('diningroom/', views.diningroom, name='diningroom'),
    path('meetingroom/', views.meetingroom, name='meetingroom'),
    path('calendar/', views.calendar, name='calendar'),
    path('message/', views.message, name='message'),
    path('kaizen/', views.improvement_create, name='improvement_create'),
    # path('kaizenEXCEL/', views.export_improvementdata_excel, name='kaizenEXCEL'),
    path('improve_list/', views.improve_list, name='improve_list'),
    path('improve_list2/', views.improve_list2, name='improve_list2'),
    path('improve_detail/<uuid:pk>', views.improve_detail, name='improve_detail'),
    path('improve_update1/<uuid:pk>', views.improve_update1, name='improve_update1'),
    path('improve_update2/<uuid:pk>', views.improve_update2, name='improve_update2'),
    path('iken/', views.opinion_create, name='opinion_create'),
#    path('improve_pdf/<uuid:pk>', views.improve_pdf, name='improve_pdf'),
    path("import_offday_csv/", views.import_offday_csv, name="import_offday_csv"),
    path("bulk_update_offday/", views.bulk_update_offday, name="bulk_update_offday"),
    path("bulk_update_offday2/", views.bulk_update_offday2, name="bulk_update_offday2"),
]

templates/base.html
<!DOCTYPE html>

{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load static %}

<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="https://cccabinet.jpn.org/bootstrap4/css/style.css">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.14.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" type='text/css' href="{% static 'css/style.css'%}">
    <script src="https://code.jquery.com/jquery-3.7.1.js"></script>
    <script src="https://code.jquery.com/ui/1.14.1/jquery-ui.js"></script>
      <title> {{ COMPANY_NAME }} </title>

    {% block extra_css %}{% endblock %}

</head>

  <body>
    <!-- ↓↓１番上のナビゲーションバー↓↓ -->
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">
          <nav class="navbar navbar-expand-lg navbar-dark fixed-top  bs-navbar">
            <div class="container-fluid">
              <a class="navbar-brand" href="/app_folder/top_page">{{ COMPANY_NAME }}</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                  {% if user.is_authenticated %}
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      掲示板
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="/app_folder/top_page">掲示板</a></li>
                      {% if user.id != EMP_ID %}
                      <li><a class="dropdown-item" href='/app_folder/info_create/'>掲示板入力</a></li>
                      {% endif %}
                    </ul>
                  </li>
                  {% if user.id != EMP_ID %}
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      入力
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="/app_folder/request_create/">申請</a></li>
                      <li><a class="dropdown-item" href="/app_folder/offday_create/">勤怠</a></li>
                      <li><a class="dropdown-item" href="/app_folder/import_offday_csv/">勤怠CSV</a></li>
                    </ul>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      申請一覧
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="/app_folder/request_list/">申請</a></li>
                      <li><a class="dropdown-item" href="/app_folder/offday_list/">勤怠</a></li>
                    </ul>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      申請検索
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="/app_folder/request_list2/">申請</a></li>
                      <li><a class="dropdown-item" href="/app_folder/offday_list2/">勤怠</a></li>
                    </ul>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      承認一覧
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="/app_folder/approval_list/">申請</a></li>
                      <li><a class="dropdown-item" href="/app_folder/ap_offday_list/">勤怠</a></li>
                      <li><a class="dropdown-item" href="/app_folder/bulk_update_offday2/">勤怠一括更新</a></li>
                    </ul>
                  </li>
                  {% if user.is_superuser %}
                  <li class="nav-item dropdown"  id="last_ap_nav">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      最終承認一覧
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="/app_folder/last_approval_list">申請</a></li>
                      <li><a class="dropdown-item" href="/app_folder/ls_offday_list/">勤怠</a></li>
                      <li><a class="dropdown-item" href="/app_folder/bulk_update_offday/">勤怠一括更新</a></li>
                    </ul>
                  </li>
                  {% endif %}
                  {% endif %}
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      スケジュール
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="/app_folder/calendar">会社カレンダー</a></li>
                      <li><a class="dropdown-item" href="/app_folder/meetingroom/">応接室</a></li>
                      <li><a class="dropdown-item" href="/app_folder/diningroom/">食堂</a></li>
                    </ul>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      改善提案
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="/app_folder/kaizen">入力</a></li>
                      {% if user.id != EMP_ID %}
                      <li><a class="dropdown-item" href="/app_folder/improve_list2">検索</a></li>
                      {% endif %}
                      <li><a class="dropdown-item" href="/app_folder/iken">社長宛意見箱</a></li>
                    </ul>
                  </li>
                  {% if user.is_staff %}
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      事務検索
                    </a>
                    <ul class="dropdown-menu">
                      <li  id ="kintai_seach_nav"><a class="dropdown-item" href="/app_folder/offday_list3/">勤怠検索</a></li>
                      <li><a class="dropdown-item" href="/app_folder/request_list3/">申請検索</a></li>
                    </ul>
                  </li>
                  {% endif %}
                  <li class="nav-item"><a class="nav-link" href="{% url 'app_folder:logout' %}" >ログアウト</a></li>
                  <li class="nav-item"><a class="nav-link" >ユーザー：{{ user.first_name }}</a></li>
                  {% else %}
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      メニュー
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="/app_folder/kaizen">改善提案</a></li>
                      <li><a class="dropdown-item" href="/app_folder/iken">社長宛意見箱</a></li>
                    </ul>
                  </li>
                  {% endif %}
                </ul>
              </div>
            </div>
          </nav>
        </div>
      </div>
    </div>


    <div id="content" class="container-fluid">
      <div class="row flex-xl-nowrap">

        <!-- ↓↓コンテンツ本体↓↓ -->
        <div class="col-12">
          {% block contents %}
          {% endblock %}
        </div>
        <!-- ↑↑コンテンツ本体ここまで↑↑ -->
      </div>
    </div>
    </div>
  </body>
</html>

<!-- サイドバーに使用しているアイコン -->
<!-- 使用できるアイコンの一覧： https://voyager-jp.com/blog/javascript/feather/ -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
<script>feather.replace()</script>
<script>
document.addEventListener('DOMContentLoaded', function() {
});
</script>